### ISSUE TITLE
Cannot use the app

### ISSUE THREAD

**Issue by vishnuraghavb** [envelop-app/envelop-web#104]
I've created my Blockstacks ID two weeks before, yet I cannot sign in to envelop.app. It always says that, 
"Your account is recent and it doesn't have its username available in the blockstack browser yet. Please try again later."
Can someone help solve this issue?

**Comment by Filmaluco** [comment]
Hi @vishnuraghavb, temporarly is not possible to create new accounts, sadly this issue is still on going with the transition to stacks 2.0 you can keep track of the issue at https://github.com/blockstack/ux/issues/946#issuecomment-777417402, we are sorry for the inconvenience.

**Comment by vishnuraghavb** [comment]
Hello @Filmaluco, Thanks for the information! But I can able to use https://blackhole.run (which also runs on blockstack) using my same blockstack ID. So, if you know could you please explain why is that? Thanks.

**Comment by Filmaluco** [comment]
@vishnuraghavb not all blockstack apps require a username to work and currently you can create accounts, you can't however register a username to that account.

Envelop links are user friendly and have the username embeded, so we do require the username to work.
`https://envelop.app/d/{username}/{file}`

Blackhole does not seem require the username, and as such can work with new accounts.

**Comment by vishnuraghavb** [comment]
Thank you for your detailed explanation! Then we all have to wait till blockstack fix the issue on their end. 
Eagerly waiting to try Envelop soon!
