### ISSUE TITLE
I can't remove pending files from my app page

### ISSUE THREAD

**Issue by filiptronicek** [envelop-app/envelop-web#59]
I wanted to upload two files (as shown by the image below) and my browser crashed, so I had to re-open the app and the upload is now stuck at 0%. So if I'm right, will they be there forever?
![image](https://user-images.githubusercontent.com/29888641/64053813-68730200-cb84-11e9-9c09-f3d2cce4b781.png)

**Comment by sdsantos** [comment]
@filiptronicek The web app doesn't have a way right now to clear those failed uploads. We have it planned, but it's not out yet. Right now the only way to clear them is by deleting them using the Android app (not practical definitely).

By the way, was the browser crash triggered by Envelop or was it unrelated?

**Comment by filiptronicek** [comment]
Ok, I'm excited to see that in the app later. 
The crash was completely unrelated because I used Chrome and using that with 4 GB of RAM (on my laptop, I mainly use my PC) wasn't the best idea 😄
