### ISSUE TITLE
Allow to organize files in folders and share folders

### ISSUE THREAD

**Issue by friedger** [envelop-app/envelop-web#78]
Currently, all files are stored in one place.
It would be nice to organize my files in folders.
Then folders should be sharable as well.

**Comment by sdsantos** [comment]
@friedger thanks for the suggestion.

Organising files in folders after they were uploaded is something we're staying away from. We would like to keep Envelop focused on sharing files and not storing them long term. 

But being able to upload and share a folder, and not just individual files, would be great, definitely 👍
