### ISSUE TITLE
Preview images and videos...

### ISSUE THREAD

**Issue by wuniversales** [envelop-app/envelop-web#81]
When you have many files it is difficult to differentiate images and videos.
I propose a preview for both...

**Comment by sdsantos** [comment]
You are right, we're only using icons right now to differentiate between types of files, and that's not enough in many situations. We're already planning to add both previews, before downloading a file, and thumbnails, for distinguishing between our own files.

You can check out our Roadmap at https://github.com/orgs/envelop-app/projects/1
