### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by mecqor** [envelop-app/envelop-web#93]
Is there a plan to translate this program into other languages?

**Comment by sdsantos** [comment]
We're planning too, but it's not high-priority for us at the moment. The Blockstack platform only supports English, and we would have 2 apps to keep localised, the web and android apps. But it's definitely a possibility.

Are you interested in any language in particular, would you be willing to help us out then?

**Comment by mecqor** [comment]
Yes, I can translate it into Persian.
I recommend the "weblate" program for localization.
