### ISSUE TITLE
Download of large files fails

### ISSUE THREAD

**Issue by jensMF** [envelop-app/envelop-web#99]
I uploaded a 3.95 GB large file to share it with friends and it seems not possible to download it. Neither in Firefox nor in Chromium. The tab always crashes during the process. In Firefox the download process goes beyond 100% an then it crashes, in Chromium the download goes to 100% and than the tab crashes.
![Screenshot_envelop](https://user-images.githubusercontent.com/1620034/99157384-93ce0800-26c8-11eb-9005-adf8689d9044.png)
![Screenshot_envelop2](https://user-images.githubusercontent.com/1620034/99158593-b23a0080-26d4-11eb-8cb3-8557d221c439.png)
![Screenshot_envelop3](https://user-images.githubusercontent.com/1620034/99158596-bf56ef80-26d4-11eb-8157-00081bfcb33b.png)

**Comment by joaodiogocosta** [comment]
Hi @jensMF, thanks for the report.

Envelop will fetch the file from [Gaia's Hub](https://github.com/blockstack/gaia) and decrypt the contents on the fly. When the file is large, it can take up all the available memory for the browser, and in fact fail if there isn't enough. This will vary from machine to machine, as the amount of available RAM will dictate the size of the file one can download.

We are working on an alternative approach that uses service workers to take advantage of the browser's download API, which will save the file to disk as it is decrypted, hopefully using just a very small portion of RAM.

In the meantime, if you want to stick with Envelop, we can suggest you to split your file in multiple and re-upload.

**Comment by jensMF** [comment]
Hi @joaodiogocosta ,
two things I find strange are:
1. I have 16GB of ram, that should be enough for a 3.95GB file, I guess?
2. Both browsers are telling me, they reached 100% firefox even 134% and after that, they crash.
How could that happen?

**Comment by joaodiogocosta** [comment]
Hi @jensMF,

The amount of RAM assigned for or utilised by the browser will vary depending on the Operating System. Given 16GB of total RAM available, your browser might just be allowed 8GB (changes over time), which will then be shared by all the tabs and child-processes. In the end, the Envelop tab will have access to a portion of the values discussed above.

In regards to tabs crashing on >= 100% memory usage, that's the browser taking precautionary measures to prevent misbehaving tabs to have an impact on other processes - so it just kills them.

Once we push the alternative approach that I mention in the previous comment, memory usage won't be a concern.

**Comment by joaodiogocosta** [comment]
Hi @jensMF, we pushed a change via #102 that hopefully fixes this for everyone. We tested it in our own machines and were able to confirm that memory usage doesn't increase significantly, or to a point of crashing the tab. I'm closing this issue for now, but feel free to share your findings.

**Comment by jensMF** [comment]
So  for chromium it is solved now. I could download my file. But for firefox it did not work. It loaded until 200% an than offered me to "download again," but I never got the chance to save the file.
![Screenshot_2021-01-19 Download file - Envelop](https://user-images.githubusercontent.com/1620034/105023432-3c8f3f80-5a4b-11eb-9a3c-88b55a52d843.png)
